import Head from 'next/head'

export default function Tailwind() {
  return (
    <div className="h-screen flex justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-medium">TailwindCSS Support</h1>
      </main>
    </div>
  )
}
